# docker-compose.yml
version: "3.9"

services:
  level1-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: level1_cpu
    tty: true
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    command: ["python", "scripts/train_level1.py", "--config", "config/train.yaml"]

  level1-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        TORCH_VER: "2.3.1"
        CUDA_TAG: "cu121"
    container_name: level1_gpu
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    command: ["python", "scripts/train_level1.py", "--config", "config/train.yaml"]
